import React from 'react';

export default function Terms() {
  return (
    <div className="policy-page-container" style={{ padding: '140px 20px', maxWidth: '850px', margin: '0 auto', color: 'var(--ink)' }}>
      <h1 style={{ fontSize: '32px', fontWeight: '900', textTransform: 'uppercase', marginBottom: '10px', letterSpacing: '-0.5px' }}>Terms & Conditions</h1>
      <p style={{ color: 'var(--grey-muted)', fontSize: '14px', marginBottom: '30px' }}>Last Updated: July 2026</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', lineHeight: '1.7', fontSize: '15px' }}>
        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Electronic Record</h2>
          <p>
            This document is an electronic record under the Information Technology Act, 2000 and applicable rules. It is generated by a computer system and does not require physical or digital signatures.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Platform</h2>
          <p>
            These Terms & Conditions govern your access to and use of https://logcloth.com/ and related services provided by LOG Clothing. By accessing, browsing, ordering, or otherwise using the website, you agree to be bound by these terms and all linked policies.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Use of Services</h2>
          <ul style={{ paddingLeft: '20px', margin: '10px 0', display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <li>You agree to provide true, accurate, and complete information while using the website or placing orders.</li>
            <li>You are responsible for all activity performed through your account or checkout information.</li>
            <li>You agree not to use the website for unlawful, illegal, fraudulent, or prohibited purposes.</li>
            <li>Unauthorized use of the website, its content, design, images, logo, or materials may lead to action under applicable law.</li>
          </ul>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Products, Pricing & Payments</h2>
          <p>
            Product descriptions, availability, prices, and offers may change without prior notice. You agree to pay the charges associated with products or services purchased through the website. Order confirmation is subject to successful validation of order details and availability.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Offer Terms</h2>
          <p style={{ marginBottom: '12px' }}>
            Products purchased under any promotional offer, including <strong>Buy 1 Get 1 Free</strong>, discounts, combo offers, or sale events, are <strong>not eligible for return or exchange</strong>.
          </p>
          <p>
            Please check the size guide carefully before placing your order. If you receive a damaged, defective, or incorrect item, contact us within <strong>48 hours</strong> of delivery, and we'll be happy to help.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Linked Policies</h2>
          <p>
            Your use of the website and transactions are also governed by our Privacy Policy, Shipping Policy, and Return, Refund & Cancellation Policy, each incorporated into these terms by reference.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Third-Party Links</h2>
          <p>
            The website may contain links to third-party websites or services. Accessing third-party links is at your discretion and will be governed by the policies of those third parties.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Indemnity & Limitation</h2>
          <p>
            You agree to indemnify and hold LOG Clothing, its affiliates, employees, and partners harmless from claims, losses, demands, penalties, or expenses arising from your breach of these terms, misuse of the website, or violation of applicable laws. We are not liable for indirect or consequential losses arising from website use, service interruptions, or events beyond our control.
          </p>
        </section>

        <section style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Governing Law</h2>
          <p>
            These terms and any disputes arising from them are governed by the laws of India and subject to the jurisdiction of competent courts in India.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '18px', fontWeight: '800', marginBottom: '10px', textTransform: 'uppercase' }}>Contact</h2>
          <p style={{ marginBottom: '8px' }}>
            For questions about these Terms & Conditions, contact <a href="mailto:contact@logcloth.com" style={{ fontWeight: '700', color: 'var(--ink)', textDecoration: 'underline' }}>contact@logcloth.com</a> or call <a href="tel:+917878623123" style={{ fontWeight: '700', color: 'var(--ink)', textDecoration: 'underline' }}>+91 7878623123</a>.
          </p>
          <p style={{ marginBottom: '4px' }}>
            <strong>Legal Name:</strong> LOGCLOTH
          </p>
          <p>
            <strong>Address:</strong> D-603, jamin green-1,vaishonavdevi circle,ahmedabad-382501
          </p>
        </section>
      </div>
    </div>
  );
}
